server:
  port: 8001
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
    #ssl:
    #key-store: classpath:7529319_www.wzhyyds.xyz.pfx
    #key-store-password: g6upI4pb
    #key-alias: tomcat
    #enabled: true.
  datasource:
    url: jdbc:mysql://localhost:3306/grbk?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/data1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    #driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wangzihao8497
  messages:
    encoding: UTF-8
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: PT24H
  application:
    name: lin_hai_bo_ke
mybatis:
  mapper-locations: classpath:mapper/mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#dubbo:
 # scan:
  #  base-packages: com.example.Service
   # protocol:
    #  name: dubbo
     # port: 20880
      #registry:
      #address: zookeeper://localhost:2181